####################################################################################
# Makefile (configuration file for GNU make - see http://www.gnu.org/software/make/)
#
# Please refer to ../Makefile for more informations on compilation options
#
all:
	$(MAKE) -C ../

%:
	$(MAKE) -C ../ $@

